/**
 * The Earth: the start of the entry animation, and a view you can come back to.
 *
 * The basemap is NASA Blue Marble Next Generation with topography and bathymetry
 * (the relief is baked into the image, so no extra maps are needed). It's only a
 * backdrop; the only things drawn on it are floats we actually have data for, and
 * no data field is ever painted on the globe.
 *
 * The images are bundled in public/ so nothing is fetched from a CDN
 * (regenerate with node scripts/fetch-textures.mjs). The shader lifts the dark
 * ocean a bit; that only affects the basemap, not the data.
 */

import * as THREE from "three";

import { TOKEN_RGB } from "./water";

/**
 * Bundled basemaps by month. Phailin is October 2013, so it uses October
 * (December has too much snow).
 *
 * 4096×2048 instead of NASA's 5400×2700: keep textures power-of-two. Mipmapping
 * the original broke the WebGL context on some drivers and the canvas went blank.
 * See scripts/fetch-textures.mjs.
 */
export const BASEMAPS = {
  october: "/world.topo.bathy.200410.4096x2048.jpg",
  december: "/world.topo.bathy.200412.4096x2048.jpg",
} as const;

export const DEFAULT_BASEMAP = BASEMAPS.october;

/** Generated by fetch-textures.mjs. Same for both months. */
export const OCEAN_MASK_URL = "/world.ocean-mask.2048x1024.jpg";

/** NASA Blue Marble clouds (credit in fetch-textures.mjs). */
export const CLOUDS_URL = "/world.clouds.2048x1024.jpg";

/** DMSP city lights. It needs its own credit line, see fetch-textures.mjs. */
export const NIGHT_LIGHTS_URL = "/world.night-lights.2048x1024.jpg";

export const GLOBE_RADIUS = 1.35;
// Layer radii, outward: clouds just above the surface, then the pins, so
// nothing z-fights.
const CLOUD_RADIUS = GLOBE_RADIUS * 1.006;
const MARKER_RADIUS = GLOBE_RADIUS * 1.008;

export const GLOBE_SUN_DIRECTION = new THREE.Vector3(0.4, 0.5, 0.75).normalize();

/**
 * Place a lat/lon on the sphere.
 *
 * Must match the fragment shader, which gets longitude from atan2(n.z, n.x) and
 * latitude from asin(n.y), or things end up in the wrong place on the texture.
 */
export function latLonToGlobe(lat: number, lon: number, radius: number): THREE.Vector3 {
  const phi = THREE.MathUtils.degToRad(lat);
  const theta = THREE.MathUtils.degToRad(lon);
  return new THREE.Vector3(
    radius * Math.cos(phi) * Math.cos(theta),
    radius * Math.sin(phi),
    radius * Math.cos(phi) * Math.sin(theta),
  );
}

/** Inverse of latLonToGlobe, for raycast hits. */
export function globeToLatLon(point: THREE.Vector3): { lat: number; lon: number } {
  const n = point.clone().normalize();
  return {
    lat: THREE.MathUtils.radToDeg(Math.asin(THREE.MathUtils.clamp(n.y, -1, 1))),
    lon: THREE.MathUtils.radToDeg(Math.atan2(n.z, n.x)),
  };
}

const SPHERE_VERTEX = /* glsl */ `
  out vec3 vNormalObject;
  out vec3 vViewNormal;
  out vec3 vViewDirObject;
  void main() {
    vNormalObject = normalize(position);
    vViewNormal = normalize(normalMatrix * normal);
    // Camera position in object space, so the specular highlight uses the same
    // un-rotated frame as uSunDirection and the day/night line.
    vec3 cameraPositionObject = (inverse(modelMatrix) * vec4(cameraPosition, 1.0)).xyz;
    vViewDirObject = normalize(cameraPositionObject - position);
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  }
`;

const SPHERE_FRAGMENT = /* glsl */ `
  precision highp float;
  in vec3 vNormalObject;
  in vec3 vViewNormal;
  in vec3 vViewDirObject;
  out vec4 fragColor;

  uniform sampler2D uBasemap;
  uniform float uHasBasemap;
  uniform sampler2D uSpecularMask;
  uniform float uHasSpecularMask;
  uniform sampler2D uNightLights;
  uniform float uHasNightLights;
  uniform vec3 uSunDirection;
  uniform vec3 uUnlit;
  uniform vec3 uRim;
  uniform float uNightFloor;
  uniform float uLift;
  uniform float uGain;
  uniform float uOpacity;
  uniform float uSpecularStrength;
  uniform float uSpecularShininess;
  uniform float uNightLightsStrength;

  const float PI = 3.141592653589793;

  void main() {
    vec3 n = normalize(vNormalObject);

    // Lat/lon from the object-space normal, so the texture stays in place however
    // the globe is rotated. (Uploaded with flipY = false, so v = 0 is the north pole.)
    float lon = atan(n.z, n.x);
    float lat = asin(clamp(n.y, -1.0, 1.0));
    vec2 uv = vec2(lon / (2.0 * PI) + 0.5, 0.5 - lat / PI);

    // Plain dark ocean until the basemap loads (or if it never does).
    vec3 surface = mix(uUnlit, texture(uBasemap, uv).rgb, uHasBasemap);

    // Lift the shadows. The Blue Marble deep ocean is only 3-12% brightness and looks
    // black on a dark page. A gamma lift brightens the darks a lot and the highlights
    // barely, so ridges and ice both stay visible (a flat multiplier would blow out
    // Antarctica). This only touches the basemap, not any data.
    surface = pow(max(surface, vec3(0.0)), vec3(1.0 / uLift));

    // Very soft day/night line. A dark night side would hide half the globe, and it's
    // used for navigation. Only scales the image's own colour, never tints it.
    float day = smoothstep(-0.75, 0.65, dot(n, normalize(uSunDirection)));
    vec3 colour = surface * mix(uNightFloor, 1.0, day) * uGain;

    // City lights on the night side, using the same terminator as the dimming.
    vec3 lights = texture(uNightLights, uv).rgb * uHasNightLights;
    colour += lights * uNightLightsStrength * (1.0 - day);

    // Sun glint on the ocean only (specular mask), on the lit side only. Fixed warm
    // white; it's just the basemap, not data.
    vec3 reflectDir = reflect(-normalize(uSunDirection), n);
    float specAngle = max(dot(reflectDir, normalize(vViewDirObject)), 0.0);
    float specular = pow(specAngle, uSpecularShininess) * texture(uSpecularMask, uv).r
      * uHasSpecularMask * day;
    colour += vec3(1.0, 0.98, 0.92) * specular * uSpecularStrength;

    // Atmosphere, brightest at the edge where you look through the most air.
    float rim = pow(1.0 - abs(dot(normalize(vViewNormal), vec3(0.0, 0.0, 1.0))), 3.0);
    colour += uRim * rim * (0.35 + 0.65 * day);

    fragColor = vec4(colour, uOpacity);
  }
`;

export interface Globe {
  group: THREE.Group;
  /** The sphere mesh, for raycasting. */
  sphere: THREE.Mesh;
  /** Resolves when the basemap has loaded (or right away if it can't). */
  ready: Promise<void>;
  /** Swap the basemap. Does nothing if that URL is already loaded. */
  setBasemap(url: string): Promise<void>;
  dispose(): void;
}

export interface GlobeOptions {
  /** Equirectangular basemap path under public/. */
  basemapUrl: string;
  /** From renderer.capabilities.getMaxAnisotropy(); helps at oblique angles. */
  maxAnisotropy?: number;
  /**
   * Ocean/land mask under public/ (see fetch-textures.mjs). Optional; without it
   * there's just no specular glint.
   */
  specularMaskUrl?: string;
  /** Night lights under public/. Optional; without it the night side is plain dark. */
  nightLightsUrl?: string;
}

export function buildGlobe({
  basemapUrl,
  maxAnisotropy = 1,
  specularMaskUrl,
  nightLightsUrl,
}: GlobeOptions): Globe {
  const group = new THREE.Group();

  const material = new THREE.ShaderMaterial({
    glslVersion: THREE.GLSL3,
    vertexShader: SPHERE_VERTEX,
    fragmentShader: SPHERE_FRAGMENT,
    uniforms: {
      uBasemap: { value: null },
      uHasBasemap: { value: 0 },
      uSpecularMask: { value: null },
      uHasSpecularMask: { value: 0 },
      uNightLights: { value: null },
      uHasNightLights: { value: 0 },
      uOpacity: { value: 1 },
      uSunDirection: { value: GLOBE_SUN_DIRECTION.clone() },
      // Fallback ocean colour if the texture is missing.
      uUnlit: { value: new THREE.Color(0.055, 0.19, 0.26) },
      uRim: { value: new THREE.Color(...TOKEN_RGB.current) },
      // Keep the night side readable so you can still find the Bay of Bengal.
      uNightFloor: { value: 0.66 },
      // Shadow lift, applied in linear space before lighting.
      uLift: { value: 1.5 },
      uGain: { value: 1.04 },
      uSpecularStrength: { value: 0.55 },
      uSpecularShininess: { value: 28 },
      uNightLightsStrength: { value: 1.4 },
    },
    transparent: true,
  });

  // 96×64 so the edge of the globe doesn't look polygonal up close.
  const sphere = new THREE.Mesh(new THREE.SphereGeometry(GLOBE_RADIUS, 96, 64), material);
  group.add(sphere);

  const loader = new THREE.TextureLoader();
  let texture: THREE.Texture | null = null;
  let loadedUrl: string | null = null;
  let specularTexture: THREE.Texture | null = null;
  let nightLightsTexture: THREE.Texture | null = null;

  // Not awaited: a missing mask just means no glint, so it doesn't hold up ready.
  if (specularMaskUrl) {
    loader.load(specularMaskUrl, (loaded) => {
      loaded.flipY = false;
      // It's a data mask, not a colour image, so no sRGB decoding.
      loaded.colorSpace = THREE.NoColorSpace;
      loaded.anisotropy = maxAnisotropy;
      loaded.wrapS = THREE.RepeatWrapping;
      loaded.wrapT = THREE.ClampToEdgeWrapping;
      loaded.minFilter = THREE.LinearMipmapLinearFilter;
      loaded.magFilter = THREE.LinearFilter;
      loaded.needsUpdate = true;

      specularTexture = loaded;
      material.uniforms.uSpecularMask!.value = loaded;
      material.uniforms.uHasSpecularMask!.value = 1;
    });
  }

  // Not awaited either; without it the night side is just dark.
  if (nightLightsUrl) {
    loader.load(nightLightsUrl, (loaded) => {
      loaded.flipY = false;
      // This one is real colour, so sRGB like the basemap.
      loaded.colorSpace = THREE.SRGBColorSpace;
      loaded.anisotropy = maxAnisotropy;
      loaded.wrapS = THREE.RepeatWrapping;
      loaded.wrapT = THREE.ClampToEdgeWrapping;
      loaded.minFilter = THREE.LinearMipmapLinearFilter;
      loaded.magFilter = THREE.LinearFilter;
      loaded.needsUpdate = true;

      nightLightsTexture = loaded;
      material.uniforms.uNightLights!.value = loaded;
      material.uniforms.uHasNightLights!.value = 1;
    });
  }

  const setBasemap = (url: string): Promise<void> => {
    if (url === loadedUrl) return Promise.resolve();
    loadedUrl = url;

    return new Promise<void>((resolve) => {
      loader.load(
        url,
        (loaded) => {
          // Another swap may have finished while this one was loading.
          if (loadedUrl !== url) {
            loaded.dispose();
            resolve();
            return;
          }
          // v = 0 has to be the top row (north pole) to match the shader.
          loaded.flipY = false;
          // No tone mapping in the renderer, so the colour space has to be set here or
          // the Earth looks washed out.
          loaded.colorSpace = THREE.SRGBColorSpace;
          loaded.anisotropy = maxAnisotropy;
          loaded.wrapS = THREE.RepeatWrapping;
          loaded.wrapT = THREE.ClampToEdgeWrapping;
          loaded.minFilter = THREE.LinearMipmapLinearFilter;
          loaded.magFilter = THREE.LinearFilter;
          loaded.needsUpdate = true;

          texture?.dispose();
          texture = loaded;
          material.uniforms.uBasemap!.value = loaded;
          material.uniforms.uHasBasemap!.value = 1;
          resolve();
        },
        undefined,
        () => {
          // The app still works without the basemap. Reset so a later retry isn't skipped.
          if (loadedUrl === url) loadedUrl = null;
          resolve();
        },
      );
    });
  };

  return {
    group,
    sphere,
    ready: setBasemap(basemapUrl),
    setBasemap,
    dispose() {
      sphere.geometry.dispose();
      material.dispose();
      texture?.dispose();
      specularTexture?.dispose();
      nightLightsTexture?.dispose();
    },
  };
}

const CLOUD_VERTEX = /* glsl */ `
  out vec3 vNormalObject;
  void main() {
    // Same object-space normal as SPHERE_VERTEX so the clouds line up with the basemap.
    vNormalObject = normalize(position);
    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  }
`;

const CLOUD_FRAGMENT = /* glsl */ `
  precision highp float;
  in vec3 vNormalObject;
  out vec4 fragColor;

  uniform sampler2D uClouds;
  uniform float uHasClouds;
  uniform vec3 uSunDirection;
  uniform float uNightFloor;
  uniform float uOpacity;

  const float PI = 3.141592653589793;

  void main() {
    vec3 n = normalize(vNormalObject);
    float lon = atan(n.z, n.x);
    float lat = asin(clamp(n.y, -1.0, 1.0));
    vec2 uv = vec2(lon / (2.0 * PI) + 0.5, 0.5 - lat / PI);

    // The cloud image is luminance (bright = cloud), used for both colour and alpha.
    float intensity = texture(uClouds, uv).r * uHasClouds;

    float day = smoothstep(-0.75, 0.65, dot(n, normalize(uSunDirection)));
    vec3 colour = vec3(1.0) * mix(uNightFloor, 1.0, day);

    fragColor = vec4(colour, intensity * uOpacity);
  }
`;

export interface CloudLayer {
  mesh: THREE.Mesh;
  /** Resolves when the clouds load, or right away if they don't. */
  ready: Promise<void>;
  dispose(): void;
}

/**
 * Thin static cloud layer just above the surface.
 *
 * Custom shader because the JPEG has no alpha channel, so alpha comes from the
 * luminance (alphaMap would read the missing alpha channel).
 */
export function buildClouds(cloudsUrl: string, maxAnisotropy = 1): CloudLayer {
  const material = new THREE.ShaderMaterial({
    glslVersion: THREE.GLSL3,
    vertexShader: CLOUD_VERTEX,
    fragmentShader: CLOUD_FRAGMENT,
    uniforms: {
      uClouds: { value: null },
      uHasClouds: { value: 0 },
      uSunDirection: { value: GLOBE_SUN_DIRECTION.clone() },
      // Keep clouds faintly visible on the night side.
      uNightFloor: { value: 0.35 },
      // 0.6 so clouds don't compete with the surface and markers.
      uOpacity: { value: 0.6 },
    },
    transparent: true,
    depthWrite: false,
  });

  const mesh = new THREE.Mesh(new THREE.SphereGeometry(CLOUD_RADIUS, 96, 64), material);

  const loader = new THREE.TextureLoader();
  let texture: THREE.Texture | null = null;

  const ready = new Promise<void>((resolve) => {
    loader.load(
      cloudsUrl,
      (loaded) => {
        loaded.flipY = false;
        // Used as luminance data, not colour, so no sRGB.
        loaded.colorSpace = THREE.NoColorSpace;
        loaded.anisotropy = maxAnisotropy;
        loaded.wrapS = THREE.RepeatWrapping;
        loaded.wrapT = THREE.ClampToEdgeWrapping;
        loaded.minFilter = THREE.LinearMipmapLinearFilter;
        loaded.magFilter = THREE.LinearFilter;
        loaded.needsUpdate = true;

        texture = loaded;
        material.uniforms.uClouds!.value = loaded;
        material.uniforms.uHasClouds!.value = 1;
        resolve();
      },
      undefined,
      () => resolve(),
    );
  });

  return {
    mesh,
    ready,
    dispose() {
      mesh.geometry.dispose();
      material.dispose();
      texture?.dispose();
    },
  };
}

/**
 * Fade the whole globe during the hand-off into the water column. The sphere uses
 * a uniform (custom shader); the rest use normal material opacity.
 */
export function setGlobeOpacity(group: THREE.Object3D, opacity: number): void {
  group.traverse((object) => {
    const material = (object as THREE.Mesh).material as THREE.Material | undefined;
    if (!material) return;
    if (material instanceof THREE.ShaderMaterial && material.uniforms.uOpacity) {
      material.uniforms.uOpacity.value = opacity;
      return;
    }
    if ("opacity" in material) {
      material.transparent = true;
      (material as THREE.LineBasicMaterial).opacity = opacity;
    }
  });
}

/**
 * Float markers on the globe: small 3D pins pointing outward from the surface.
 * They're shaded, so they stay visible over any part of the basemap.
 *
 * Real geometry has no minimum pixel size, so we rescale the pins each frame
 * relative to PIN_REFERENCE_DISTANCE (the default globe distance), up to
 * PIN_MAX_SCALE.
 */

/** What the markers get each frame from scene.ts tick(). */
interface MarkerFrame {
  time: number;
  cameraDistance: number;
}

export interface FloatMarkers {
  object: THREE.Object3D;
  update(frame: MarkerFrame): void;
  dispose(): void;
}

const PIN_STEM_HEIGHT = 0.052;
const PIN_STEM_RADIUS = 0.0018;
const PIN_HEAD_RADIUS = 0.014;
const PIN_SHADOW_RADIUS = 0.016;
/** Camera distance the pin size is tuned for. */
const PIN_REFERENCE_DISTANCE = 4.05;
/** Max pin growth when zoomed out, so they don't get huge. */
const PIN_MAX_SCALE = 3;

/** Shared vertex shader for the pin stem and head (world-space normal and view dir). */
const PIN_COMMON_VERTEX = /* glsl */ `
  out vec3 vNormalWorld;
  out vec3 vViewDir;
  void main() {
    vec4 worldPosition = modelMatrix * instanceMatrix * vec4(position, 1.0);
    vNormalWorld = normalize(mat3(modelMatrix) * mat3(instanceMatrix) * normal);
    vViewDir = normalize(cameraPosition - worldPosition.xyz);
    gl_Position = projectionMatrix * viewMatrix * worldPosition;
  }
`;

/** Pin head fragment shader (glossy bead). */
const PIN_HEAD_FRAGMENT = /* glsl */ `
  precision highp float;
  in vec3 vNormalWorld;
  in vec3 vViewDir;
  out vec4 fragColor;

  uniform vec3 uColor;
  uniform vec3 uSunDirection;
  uniform float uOpacity;

  void main() {
    vec3 n = normalize(vNormalWorld);
    vec3 sun = normalize(uSunDirection);
    vec3 view = normalize(vViewDir);

    float lambert = max(dot(n, sun), 0.0);
    // Sharp specular highlight on the pin head
    vec3 reflectDir = reflect(-sun, n);
    float specAngle = max(dot(reflectDir, view), 0.0);
    float specular = pow(specAngle, 32.0);

    // Rim highlight
    float rim = pow(1.0 - max(dot(view, n), 0.0), 2.5);

    vec3 diffuse = uColor * mix(0.45, 1.15, lambert);
    vec3 shaded = diffuse + vec3(1.0, 0.98, 0.95) * specular * 0.95 + vec3(1.0, 0.6, 0.5) * rim * 0.4;

    fragColor = vec4(shaded, uOpacity);
  }
`;

/** Pin stem fragment shader (steel needle). */
const PIN_STEM_FRAGMENT = /* glsl */ `
  precision highp float;
  in vec3 vNormalWorld;
  in vec3 vViewDir;
  out vec4 fragColor;

  uniform vec3 uSunDirection;
  uniform float uOpacity;

  // Steel needle colours
  const vec3 STEEL_BRIGHT = vec3(0.88, 0.91, 0.96);
  const vec3 STEEL_DARK = vec3(0.38, 0.42, 0.48);

  void main() {
    vec3 n = normalize(vNormalWorld);
    vec3 sun = normalize(uSunDirection);
    vec3 view = normalize(vViewDir);

    float lambert = max(dot(n, sun), 0.0);
    vec3 reflectDir = reflect(-sun, n);
    float specAngle = max(dot(reflectDir, view), 0.0);
    float specular = pow(specAngle, 18.0);

    vec3 shaded = mix(STEEL_DARK, STEEL_BRIGHT, lambert) + vec3(0.95, 0.98, 1.0) * specular * 0.65;
    fragColor = vec4(shaded, uOpacity);
  }
`;

/** Pin shadow vertex shader. */
const PIN_SHADOW_VERTEX = /* glsl */ `
  out vec2 vUv;
  void main() {
    vUv = uv;
    vec4 worldPosition = modelMatrix * instanceMatrix * vec4(position, 1.0);
    gl_Position = projectionMatrix * viewMatrix * worldPosition;
  }
`;

/** Soft shadow on the globe under each pin. */
const PIN_SHADOW_FRAGMENT = /* glsl */ `
  precision highp float;
  in vec2 vUv;
  out vec4 fragColor;

  uniform float uOpacity;

  void main() {
    float dist = length(vUv - vec2(0.5)) * 2.0;
    if (dist > 1.0) discard;
    float alpha = smoothstep(1.0, 0.15, dist) * 0.52 * uOpacity;
    fragColor = vec4(0.01, 0.03, 0.07, alpha);
  }
`;

export function buildFloatMarkers(positions: { lat: number; lon: number }[]): FloatMarkers | null {
  if (positions.length === 0) return null;

  // 1. stem
  const stemGeometry = new THREE.CylinderGeometry(PIN_STEM_RADIUS, PIN_STEM_RADIUS, PIN_STEM_HEIGHT, 12);
  stemGeometry.translate(0, PIN_STEM_HEIGHT / 2, 0);

  const stemMaterial = new THREE.ShaderMaterial({
    glslVersion: THREE.GLSL3,
    vertexShader: PIN_COMMON_VERTEX,
    fragmentShader: PIN_STEM_FRAGMENT,
    uniforms: {
      uSunDirection: { value: GLOBE_SUN_DIRECTION.clone() },
      uOpacity: { value: 1.0 },
    },
    transparent: true,
  });

  // 2. head
  const headGeometry = new THREE.SphereGeometry(PIN_HEAD_RADIUS, 20, 16);
  headGeometry.translate(0, PIN_STEM_HEIGHT, 0);

  const headMaterial = new THREE.ShaderMaterial({
    glslVersion: THREE.GLSL3,
    vertexShader: PIN_COMMON_VERTEX,
    fragmentShader: PIN_HEAD_FRAGMENT,
    uniforms: {
      // Bright red head so it stands out against the ocean.
      uColor: { value: new THREE.Color(1.0, 0.18, 0.32) },
      uSunDirection: { value: GLOBE_SUN_DIRECTION.clone() },
      uOpacity: { value: 1.0 },
    },
    transparent: true,
  });

  // 3. shadow disc
  const shadowGeometry = new THREE.CircleGeometry(PIN_SHADOW_RADIUS, 18);
  shadowGeometry.rotateX(-Math.PI / 2);
  shadowGeometry.translate(0.005, 0.0004, 0.005);

  const shadowMaterial = new THREE.ShaderMaterial({
    glslVersion: THREE.GLSL3,
    vertexShader: PIN_SHADOW_VERTEX,
    fragmentShader: PIN_SHADOW_FRAGMENT,
    uniforms: {
      uOpacity: { value: 1.0 },
    },
    transparent: true,
    depthWrite: false,
  });

  const count = positions.length;
  const stemMesh = new THREE.InstancedMesh(stemGeometry, stemMaterial, count);
  const headMesh = new THREE.InstancedMesh(headGeometry, headMaterial, count);
  const shadowMesh = new THREE.InstancedMesh(shadowGeometry, shadowMaterial, count);

  const up = new THREE.Vector3(0, 1, 0);
  const basePositions: THREE.Vector3[] = [];
  const baseQuaternions: THREE.Quaternion[] = [];

  positions.forEach(({ lat, lon }) => {
    const point = latLonToGlobe(lat, lon, MARKER_RADIUS);
    basePositions.push(point);
    baseQuaternions.push(new THREE.Quaternion().setFromUnitVectors(up, point.clone().normalize()));
  });

  const matrix = new THREE.Matrix4();
  const scaleVector = new THREE.Vector3(1, 1, 1);
  const applyScale = (scale: number) => {
    scaleVector.setScalar(scale);
    for (let i = 0; i < basePositions.length; i++) {
      matrix.compose(basePositions[i]!, baseQuaternions[i]!, scaleVector);
      stemMesh.setMatrixAt(i, matrix);
      headMesh.setMatrixAt(i, matrix);
      shadowMesh.setMatrixAt(i, matrix);
    }
    stemMesh.instanceMatrix.needsUpdate = true;
    headMesh.instanceMatrix.needsUpdate = true;
    shadowMesh.instanceMatrix.needsUpdate = true;
  };
  applyScale(1);

  const group = new THREE.Group();
  group.add(shadowMesh);
  group.add(stemMesh);
  group.add(headMesh);

  return {
    object: group,
    update({ cameraDistance }) {
      const scale = THREE.MathUtils.clamp(cameraDistance / PIN_REFERENCE_DISTANCE, 0.85, PIN_MAX_SCALE);
      applyScale(scale);
    },
    dispose() {
      stemGeometry.dispose();
      stemMaterial.dispose();
      headGeometry.dispose();
      headMaterial.dispose();
      shadowGeometry.dispose();
      shadowMaterial.dispose();
    },
  };
}


/** Much further out than the max camera distance (9) so there's no visible parallax. */
const STARFIELD_RADIUS = 45;

/**
 * Uniform random point on a sphere (normalising random xyz would bunch toward
 * the cube's corners).
 */
function randomOnSphere(radius: number): THREE.Vector3 {
  const u = Math.random();
  const v = Math.random();
  const theta = 2 * Math.PI * u;
  const phi = Math.acos(2 * v - 1);
  return new THREE.Vector3(
    radius * Math.sin(phi) * Math.cos(theta),
    radius * Math.sin(phi) * Math.sin(theta),
    radius * Math.cos(phi),
  );
}

function starLayer(count: number, size: number, opacity: number, warmth: number): THREE.Points {
  const positions = new Float32Array(count * 3);
  const colors = new Float32Array(count * 3);
  const color = new THREE.Color();

  for (let i = 0; i < count; i++) {
    randomOnSphere(STARFIELD_RADIUS).toArray(positions, i * 3);

    // Mostly white with a slight blue or warm tint.
    const hue = Math.random() < warmth ? 0.08 + Math.random() * 0.05 : 0.58 + Math.random() * 0.08;
    const lightness = 0.7 + Math.random() * 0.3;
    color.setHSL(hue, 0.35, lightness);
    color.toArray(colors, i * 3);
  }

  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute("position", new THREE.BufferAttribute(positions, 3));
  geometry.setAttribute("color", new THREE.BufferAttribute(colors, 3));

  return new THREE.Points(
    geometry,
    new THREE.PointsMaterial({
      size,
      sizeAttenuation: false,
      vertexColors: true,
      transparent: true,
      opacity,
      depthWrite: false,
    }),
  );
}

/**
 * Starfield behind the globe. Two layers (many dim stars, fewer bright ones)
 * for variety, since PointsMaterial has one size per material.
 */
export function buildStarfield(): THREE.Group {
  const group = new THREE.Group();
  group.add(starLayer(3200, 1.1, 0.55, 0.12));
  group.add(starLayer(220, 2.1, 0.85, 0.12));
  return group;
}
